apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-alpine
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    # path to the folder with the YAML manifests
    path: course_files/exercises/manifests
    repoURL: https://github.com/ekpoesua/Cloud-Native-Foundations
    targetRevision: HEAD
  # Sync policy
  syncPolicy: {}
