name: build-and-push-docker-image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      
      - run: cd course_files/solutions/python-helloworld
      - run: pwd

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.5.0
        id: buildx
        with:
          install: true


      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      - name: Build and push Docker images
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          push: true
          tags: esuaekpo/python-helloworld:latest
          platforms: linux/amd64,linux/arm64


